FROM resin/%%RESIN_MACHINE_NAME%%-debian

ENV INITSYSTEM on

RUN apt-get -q update && apt-get install -yq --no-install-recommends \
	cron \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

COPY . /usr/src/app/
WORKDIR /usr/src/app

RUN echo "*/1 * * * * /usr/src/app/job.sh" | crontab

CMD ["/bin/bash", "start.sh"]
