FROM resin/%%RESIN_MACHINE_NAME%%-systemd

ENV INITSYSTEM on

RUN apt-get update && apt-get install -y cron && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY . /usr/src/app/
WORKDIR /usr/src/app

RUN echo "*/1 * * * * /usr/src/app/job.sh" | crontab

CMD start.sh
